import type {Analysis,Candidate} from '../types';
import {Plot,colors} from './Plot';
export function AnalysisPanel({analysis,candidates,onCandidate,disabled}:{analysis:Analysis|null;candidates:Candidate[];onCandidate:(c:Candidate)=>void;disabled:boolean}){
 if(!analysis)return <div className="analysis-empty"><div className="eyebrow">DU SIGNAL AU MODÈLE</div><h2>Écouter. Mesurer. Expliquer.</h2><p>Importez une note isolée, choisissez la fenêtre d’analyse, puis lancez l’extraction des caractéristiques.</p><div className="analysis-steps"><span>01 <b>Fondamentale</b><small>Autocorrélation</small></span><span>02 <b>Partiels</b><small>Fréquence · amplitude · phase</small></span><span>03 <b>Décroissance</b><small>Enveloppe de chaque mode</small></span></div></div>;
 return <div className="analysis-content"><div className="analysis-stats"><div><label>Fondamentale estimée</label><strong>{analysis.f0?.toFixed(2)??'Indéterminée'} <small>{analysis.f0?'Hz':''}</small></strong></div><div><label>Partiels résolus</label><strong>{analysis.partials.length}</strong></div><div><label>Attaque du modèle</label><strong>{(analysis.attack*1000).toFixed(2)} <small>ms</small></strong></div><div><label>Inharmonicité B</label><strong>{analysis.inharmonicity?.B.toExponential(2)??'Non établie'}</strong></div></div>
 <div className="analysis-columns"><div><div className="section-small">Partiels mesurés <span>R² = qualité de la régression de décroissance</span></div><div className="table-scroll"><table><thead><tr><th>Mode</th><th>f (Hz)</th><th>Amplitude</th><th>τ (s)</th><th>R²</th></tr></thead><tbody>{analysis.partials.map((p,i)=><tr key={i}><td><span className="mode-index">{String(i+1).padStart(2,'0')}</span></td><td>{p.frequency.toFixed(2)}</td><td>{p.amplitude.toFixed(4)}</td><td>{p.tau.toFixed(3)}</td><td>{p.decay_r2?.toFixed(3)??'—'}</td></tr>)}</tbody></table></div></div><div><div className="section-small">Enveloppe RMS mesurée</div><Plot height={190} data={[{x:analysis.envelope.time,y:analysis.envelope.amplitude,type:'scatter',mode:'lines',fill:'tozeroy',line:{color:colors.original,width:1.5},fillcolor:'#9bd5ea15'}]}/><p className="method-note">{analysis.method}</p>{analysis.inharmonicity&&<p className="method-note">Ajustement de B sur {analysis.inharmonicity.count} partiels · RMSE {analysis.inharmonicity.rmse_hz.toFixed(3)} Hz. {analysis.inharmonicity.method}</p>}</div></div>
 {candidates.length>0&&<><div className="section-small">Modèles candidats <span>Choisir un modèle pour l’écouter et l’éditer</span></div><div className="candidate-list">{candidates.map((c,i)=><button key={i} disabled={disabled} onClick={()=>onCandidate(c)}><span className="candidate-number">{String(i+1).padStart(2,'0')}</span><span><b>{c.patch.name}</b><small>{c.modules??(c.patch.nodes.length+c.patch.nodes.filter(n=>n.type==='modal').length)} modules · {c.generators!==undefined?`${c.generators} générateurs · ${c.parameter_count} paramètres`:`complexité ${c.complexity.toFixed(1)}`}</small></span><span><b>{c.errors.total.toFixed(4)}</b><small>erreur</small></span><span><b>{c.within_tolerance!==undefined?(c.reference?'Référence':c.within_tolerance?'Admissible':'Hors budget'):c.score.toFixed(4)}</b><small>{c.within_tolerance!==undefined?(c.pareto?'Compromis efficace':'Candidat comparé'):'score'}</small>{c.rejection_reasons?.length? <small className="candidate-reasons">{c.rejection_reasons.join(' · ')}</small>:null}</span></button>)}</div></>}
 <details className="assumptions" open><summary>Hypothèses et limites de l’identification</summary>{analysis.warnings.map(w=><p key={w}>{w}</p>)}</details></div>
}
