import {useEffect,useState} from 'react';
import {Copy,Trash2,Info,ChevronDown} from 'lucide-react';
import type {Block,Catalog,Transfer} from '../types';
import {api} from '../api';
import {Plot,colors} from './Plot';
export function Inspector({block,catalog,fs,onParameter,onDelete,onDuplicate,locked,selectedParameters,onToggleParameter}:{block?:Block;catalog:Catalog;fs:number;onParameter:(key:string,value:number)=>void;onDelete:()=>void;onDuplicate:()=>void;locked:boolean;selectedParameters:string[];onToggleParameter:(id:string)=>void}){
 const [tf,setTf]=useState<Transfer|null>(null),[error,setError]=useState(''),[view,setView]=useState('bode');
 useEffect(()=>{setTf(null);setError('');if(!block)return;const controller=new AbortController();const timer=setTimeout(()=>api<Transfer>('/transfer',{node:block,sample_rate:fs},controller.signal).then(setTf).catch(e=>{if(e.name!=='AbortError')setError(e.message)}),150);return()=>{clearTimeout(timer);controller.abort()}},[block,fs]);
 if(!block)return <aside className="inspector"><div className="panel-label">INSPECTEUR</div><div className="inspector-empty"><Sliders/><h3>Chaque bloc s’explique.</h3><p>Sélectionnez un composant pour modifier ses paramètres et explorer son modèle mathématique.</p></div><div className="scientific-note"><Info size={16}/><p>Les blocs du schéma sont les blocs réellement exécutés par le moteur audio.</p></div></aside>;
 const def=catalog[block.type];if(!def)return null;
 return <aside className="inspector"><div className="inspector-top"><div><div className="panel-label">INSPECTEUR / {block.type.toUpperCase()}</div><h3>{def.label}</h3></div><div className="icon-actions"><button title="Dupliquer" aria-label="Dupliquer le bloc" disabled={locked||block.type==='output'} onClick={onDuplicate}><Copy size={15}/></button><button title="Supprimer" aria-label="Supprimer le bloc" disabled={locked} onClick={onDelete}><Trash2 size={15}/></button></div></div>
 <div className="inspector-section"><div className="section-small">Paramètres <span>☑ optimiser</span></div>{Object.entries(def.parameters).map(([key,p])=><div className="parameter" key={key}><label htmlFor={`p-${key}`}>{p.label}</label><div className="parameter-input"><input type="checkbox" aria-label={`Optimiser ${p.label}`} disabled={locked||key==='seed'} checked={selectedParameters.includes(`${block.id}:${key}`)} onChange={()=>onToggleParameter(`${block.id}:${key}`)}/><input id={`p-${key}`} type="number" step="any" disabled={locked} value={block.parameters[key]??p.default} min={p.minimum} max={['fc','frequency'].includes(key)?Math.min(p.maximum,fs*.499):p.maximum} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))onParameter(key,e.target.valueAsNumber)}}/><span>{p.unit||'—'}</span></div></div>)}{!Object.keys(def.parameters).length&&<p className="muted">Ce bloc n’a pas de paramètre réglable.</p>}</div>
 <div className="inspector-section"><div className="section-small">Modèle mathématique</div><code className="equation">{def.equation}</code><p>{def.description}</p>{error&&<p className="error-inline">{error}</p>}{tf?.digital&&<><div className="section-small">Implémentation numérique</div><code className="equation small">{tf.digital}</code><div className="transfer-facts"><span>Ordre <b>{tf.order}</b></span><span>Gain DC <b>{tf.dc_gain?.toPrecision(4)}</b></span><span className={tf.stable?'green':'orange'}>{tf.stable?'● Stable':'● Instable'}</span></div><details><summary>Pôles et zéros <ChevronDown size={13}/></summary><pre>{JSON.stringify({poles:tf.poles,zeros:tf.zeros},null,2)}</pre></details></>}{tf&&!tf.lti&&<span className="tag">Bode LTI non applicable</span>}</div>
 {tf?.lti&&<div className="inspector-section bode"><div className="mini-tabs"><button className={view==='bode'?'active':''} onClick={()=>setView('bode')}>Bode H(z)</button><button className={view==='impulse'?'active':''} onClick={()=>setView('impulse')}>Impulsion</button></div>{view==='bode'?<><Plot height={175} data={[{x:tf.frequency,y:tf.magnitude,type:'scatter',mode:'lines',line:{color:colors.model,width:2},hovertemplate:'%{x:.1f} Hz · %{y:.2f} dB<extra></extra>'}]} layout={{xaxis:{type:'log',title:{text:'Fréquence (Hz)'},gridcolor:'#28333e'},yaxis:{title:{text:'Gain (dB)'},gridcolor:'#28333e'}}}/><Plot height={155} data={[{x:tf.frequency,y:tf.phase,type:'scatter',mode:'lines',line:{color:colors.original,width:1.5}}]} layout={{xaxis:{type:'log',title:{text:'Fréquence (Hz)'},gridcolor:'#28333e'},yaxis:{title:{text:'Phase (°)'},gridcolor:'#28333e'}}}/></>:<Plot height={200} data={[{x:tf.impulse_time,y:tf.impulse,type:'scatter',mode:'lines'}]}/>}</div>}
 <div className="inspector-section"><div className="section-small">Pourquoi ce bloc ?</div><p>{block.reason||'Composant défini manuellement ; aucun motif d’identification automatique.'}</p></div></aside>
}
function Sliders(){return <svg width="44" height="44" viewBox="0 0 44 44" fill="none" stroke="currentColor"><path d="M8 5v34M22 5v34M36 5v34"/><path strokeWidth="5" d="M8 12v6M22 25v6M36 16v6"/></svg>}
