import {useEffect,useMemo,useRef,useState} from 'react';
import type {Patch} from '../types';
import {api} from '../api';
type MidiInput={id:string;name?:string;onmidimessage:((event:{data:Uint8Array})=>void)|null};
type MidiAccess={inputs:Map<string,MidiInput>;onstatechange:(()=>void)|null};
const noteName=(n:number)=>['Do','Do♯','Ré','Ré♯','Mi','Fa','Fa♯','Sol','Sol♯','La','La♯','Si'][n%12]+(Math.floor(n/12)-1);
export function Keyboard({patch,disabled,onPatch,onError}:{patch:Patch;disabled:boolean;onPatch:(p:Patch)=>void;onError:(s:string)=>void}){
 const [reference,setReference]=useState(69),[octave,setOctave]=useState(60),[velocity,setVelocity]=useState(100),[track,setTrack]=useState(true),[message,setMessage]=useState('Préparez le montage pour afficher le VCA de vélocité et l’ADSR de relâchement.'),[preparing,setPreparing]=useState(false),[active,setActive]=useState<number[]>([]),[midi,setMidi]=useState(''),[volume,setVolume]=useState(.5);
 const ctx=useRef<AudioContext|null>(null),cache=useRef(new Map<number,AudioBuffer>()),pending=useRef(new Map<number,Promise<AudioBuffer>>()),voices=useRef(new Map<number,{source:AudioBufferSourceNode;gain:GainNode}>()),held=useRef(new Map<number,number>()),generation=useRef(0),access=useRef<MidiAccess|null>(null),controllers=useRef(new Set<AbortController>()),queue=useRef<Promise<unknown>>(Promise.resolve()),disposed=useRef(false);
 const ready=patch.nodes.some(n=>n.id==='keyboard-adsr');
 const signature=useMemo(()=>JSON.stringify({patch:{...patch,nodes:patch.nodes.map(({position,...n})=>n)},reference,track}),[patch,reference,track]);
 function stopAll(){held.current.clear();for(const v of voices.current.values()){v.source.stop();v.gain.disconnect()}voices.current.clear();setActive([])}
 useEffect(()=>{generation.current++;for(const c of controllers.current)c.abort();controllers.current.clear();cache.current.clear();pending.current.clear();stopAll()},[signature]);
 useEffect(()=>{disposed.current=false;return()=>{disposed.current=true;generation.current++;for(const c of controllers.current)c.abort();for(const v of voices.current.values())v.source.stop();for(const input of access.current?.inputs.values()??[])input.onmidimessage=null;if(access.current)access.current.onstatechange=null;void ctx.current?.close()}},[]);
 async function audio(){if(!ctx.current)ctx.current=new AudioContext();await ctx.current.resume();return ctx.current}
 async function buffer(note:number):Promise<AudioBuffer>{
  if(cache.current.has(note))return cache.current.get(note)!;
  if(pending.current.has(note))return pending.current.get(note)!;
  const version=generation.current;
  const work=queue.current.catch(()=>{}).then(async()=>{if(version!==generation.current)throw new DOMException('Modèle modifié','AbortError');const c=new AbortController();controllers.current.add(c);try{const response=await fetch('/api/instrument/note',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patch,note,reference_note:reference,velocity:127,gate:60,track_filters:track}),signal:c.signal});if(!response.ok){const e=await response.json();throw Error(typeof e.detail==='string'?e.detail:'Calcul de note impossible.')}const data=await response.arrayBuffer();if(version!==generation.current)throw new DOMException('Modèle modifié','AbortError');const decoded=await ctx.current!.decodeAudioData(data);if(version!==generation.current)throw new DOMException('Modèle modifié','AbortError');cache.current.set(note,decoded);while(cache.current.size>24)cache.current.delete(cache.current.keys().next().value!);if(Number(response.headers.get('X-Muted-Partials'))>0)setMessage('Certains partiels dépassent Nyquist sur cette note et ont été coupés.');return decoded}finally{controllers.current.delete(c)}});
  queue.current=work;pending.current.set(note,work);try{return await work}finally{if(pending.current.get(note)===work)pending.current.delete(note)}
 }
 async function noteOn(note:number,v:number){if(!ready||disabled||note<21||note>108)return;const token=(held.current.get(note)??0)+1;held.current.set(note,token);const version=generation.current;try{const c=await audio();if(!cache.current.has(note))setMessage(`Calcul de ${noteName(note)}… Première lecture à la demande.`);const data=await buffer(note);if(disposed.current||version!==generation.current||held.current.get(note)!==token)return;voices.current.get(note)?.source.stop();if(voices.current.size>=8){const old=voices.current.keys().next().value!;voices.current.get(old)!.source.stop();voices.current.delete(old)}const source=c.createBufferSource(),gain=c.createGain();source.buffer=data;gain.gain.value=v/127*volume;source.connect(gain);gain.connect(c.destination);source.onended=()=>{gain.disconnect();if(voices.current.get(note)?.source===source){voices.current.delete(note);if(!disposed.current)setActive([...voices.current.keys()])}};voices.current.set(note,{source,gain});source.start();setActive([...voices.current.keys()]);setMessage(`${noteName(note)} · MIDI ${note} · ${cache.current.size} notes en cache`)}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;onError(String(e))}}
 function noteOff(note:number){held.current.delete(note);const voice=voices.current.get(note);if(!voice||!ctx.current)return;const now=ctx.current.currentTime;const release=patch.nodes.find(n=>n.id==='keyboard-adsr')?.parameters.release??.2;voice.gain.gain.cancelScheduledValues(now);voice.gain.gain.setValueAtTime(voice.gain.gain.value,now);voice.gain.gain.linearRampToValueAtTime(0,now+release);voice.source.stop(now+release+.005);voices.current.delete(note);setActive([...voices.current.keys()])}
 async function prepare(){try{const p=await api<Patch>('/instrument/prepare',patch);const frequencies=p.nodes.filter(n=>n.type==='oscillator').map(n=>n.parameters.frequency);if(frequencies.length)setReference(Math.max(21,Math.min(108,Math.round(69+12*Math.log2(Math.min(...frequencies)/440)))));onPatch(p);setMessage('Montage prêt. Vérifiez la note de référence, puis préparez l’octave pour jouer sans calcul à la première frappe.')}catch(e){onError(String(e))}}
 async function prewarm(){setPreparing(true);const version=generation.current;try{await audio();for(let n=octave;n<octave+12&&n<=108;n++){if(version!==generation.current)break;await buffer(n);setMessage(`Préparation ${noteName(n)} · ${n-octave+1}/12`)}if(version===generation.current)setMessage('Octave prête : notes resynthétisées en cache, jusqu’à 8 voix.')}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))onError(String(e))}finally{setPreparing(false)}}
 const handlers=useRef({noteOn,noteOff});handlers.current={noteOn,noteOff};
 async function connectMidi(){try{await audio();const nav=navigator as unknown as {requestMIDIAccess?:(options:{sysex:boolean})=>Promise<MidiAccess>};if(!nav.requestMIDIAccess)throw Error('MIDI indisponible dans ce navigateur. Le clavier à l’écran reste utilisable ; essayer un navigateur compatible en HTTPS.');const a=await nav.requestMIDIAccess({sysex:false});if(disposed.current)return;access.current=a;const bind=()=>{const names:string[]=[];for(const input of a.inputs.values()){names.push(input.name??input.id);input.onmidimessage=e=>{const [status,n,v]=e.data;const kind=status&240;if(kind===144&&v>0)void handlers.current.noteOn(n,v);else if(kind===128||kind===144)handlers.current.noteOff(n);else if(kind===176&&(n===120||n===123))stopAll()}}setMidi(names.join(', ')||'Aucune entrée détectée')};a.onstatechange=bind;bind()}catch(e){onError(String(e))}}
 return <section className="keyboard-panel"><div className="keyboard-heading"><b>CLAVIER / MIDI · modèle transposable</b><button disabled={disabled||preparing||ready} onClick={()=>void prepare()}>{ready?'Montage préparé':'Préparer le montage'}</button><button disabled={!ready||disabled||preparing} onClick={()=>void connectMidi()}>Connecter MIDI</button><button onClick={stopAll}>Tout arrêter</button></div><div className="keyboard-controls"><label>Note de référence<input aria-label="Note MIDI de référence" type="number" min="21" max="108" disabled={preparing} value={reference} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))setReference(Math.max(21,Math.min(108,Math.round(e.target.valueAsNumber))))}}/></label><label>Octave<select value={octave} disabled={preparing} onChange={e=>setOctave(+e.target.value)}>{[24,36,48,60,72,84,96].map(n=><option key={n} value={n}>{noteName(n)} – {noteName(n+11)}</option>)}</select></label><label>Vélocité<input type="number" min="1" max="127" value={velocity} onChange={e=>setVelocity(Math.max(1,Math.min(127,+e.target.value)))}/></label><label>Volume<input aria-label="Volume clavier" type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(+e.target.value)}/></label><label><input type="checkbox" checked={track} disabled={preparing} onChange={e=>setTrack(e.target.checked)}/> Filtres tonals suivent la note</label><button disabled={!ready||disabled||preparing} onClick={()=>void prewarm()}>{preparing?'Préparation…':'Préparer cette octave'}</button></div><div className="piano-keys">{Array.from({length:12},(_,i)=>octave+i).map(n=><button key={n} disabled={!ready||disabled} className={`${[1,3,6,8,10].includes(n%12)?'black':''} ${active.includes(n)?'playing':''}`} aria-label={`Jouer ${noteName(n)}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);void noteOn(n,velocity)}} onPointerUp={()=>noteOff(n)} onPointerCancel={()=>noteOff(n)} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();void noteOn(n,velocity)}}} onKeyUp={e=>{if(e.key===' '||e.key==='Enter')noteOff(n)}}>{noteName(n)}</button>)}</div><p role="status">{message}{midi&&` · MIDI : ${midi}`}</p><small>Notes MIDI 21–108. Chaque note est recalculée depuis les oscillateurs et filtres, puis mise en cache ; le WAV source n’est pas rejoué. Le relâchement utilise l’ADSR affiché. La fidélité sur tout le clavier et selon la vélocité nécessite plusieurs enregistrements de référence.</small></section>
}
