import type {Patch,AudioData,Analysis,RenderResult,Weights,Transfer,SignalView} from './types';
import {api,download,exportBlob} from './api';
const escape=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function chart(x:number[],ys:{y:number[];color:string;name:string}[],title:string,log=false){
 if(!x.length)return '';const xx=x.map(v=>log?Math.log10(Math.max(1,v)):v),min=xx[0],max=xx[xx.length-1];let low=Infinity,high=-Infinity;ys.forEach(s=>s.y.forEach(v=>{low=Math.min(low,v);high=Math.max(high,v)}));
 const paths=ys.map(s=>`<polyline points="${s.y.map((v,i)=>`${50+700*(xx[i]-min)/(max-min||1)},${180-145*(v-low)/(high-low||1)}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="1"/>`);
 return `<figure><figcaption>${escape(title)} — ${ys.map(s=>escape(s.name)).join(' / ')}</figcaption><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 220"><rect width="800" height="220" fill="#f5f7fa"/>${paths.join('')}<text x="5" y="22" font-size="11">${high.toPrecision(3)}</text><text x="5" y="180" font-size="11">${low.toPrecision(3)}</text><text x="50" y="210" font-size="11">${x[0].toPrecision(3)}</text><text x="710" y="210" font-size="11">${x[x.length-1].toPrecision(3)}</text></svg></figure>`
}
function spectrogram(view:SignalView,label:string){const s=view.spectrogram;const c=document.createElement('canvas');c.width=s.time.length;c.height=s.frequency.length;const ctx=c.getContext('2d')!;s.db.forEach((row,j)=>row.forEach((db,i)=>{const v=Math.max(0,Math.min(1,(db+100)/100));ctx.fillStyle=`rgb(${Math.round(10+225*v)},${Math.round(20+210*v)},${Math.round(35+80*v)})`;ctx.fillRect(i,c.height-j-1,1,1)}));return `<figure><figcaption>Spectrogramme ${escape(label)} · 0–${s.frequency.at(-1)?.toFixed(0)} Hz · 0–${view.duration.toFixed(3)} s · échelle −100 à 0 dBFS</figcaption><img alt="Spectrogramme ${escape(label)}" src="${c.toDataURL()}" style="width:100%;height:220px;image-rendering:pixelated"/></figure>`}
export async function exportReport(patch:Patch,audio:AudioData|null,analysis:Analysis|null,result:RenderResult|null,weights:Weights,start:number){
 patch=await api<Patch>('/patch/validate',patch);
 const graph=await (await exportBlob('/export/svg',patch)).text();
 const transfers=await Promise.all(patch.nodes.map(node=>api<Transfer>('/transfer',{node,sample_rate:patch.sample_rate})));
 let plots='';for(const [label,v] of [['Original',result?.reference],['Synthèse',result?.view],['Résidu',result?.difference]] as const){if(!v)continue;plots+=chart(v.time,[{y:v.wave,color:'#35677a',name:label}],`${label} : amplitude / temps (s)`)+chart(v.frequency,[{y:v.spectrum,color:'#476935',name:label}],`${label} : dBFS / fréquence (Hz, log)`,true)+spectrogram(v,label)}
 const math=patch.nodes.map((n,i)=>{const tf=transfers[i];return `<section><h3>${escape(n.label||n.type)}</h3><p>${escape(n.reason)}</p><pre>${escape(JSON.stringify(n.parameters,null,2))}</pre><p>${escape(tf.equation)}</p><p>${escape(tf.description)}</p>${tf.digital?`<pre>${escape(tf.digital)}</pre><p>Ordre ${tf.order} · gain DC ${tf.dc_gain} · stable ${tf.stable}</p><pre>${escape(JSON.stringify({poles:tf.poles,zeros:tf.zeros},null,2))}</pre>`:''}${tf.frequency&&tf.magnitude&&tf.phase?chart(tf.frequency,[{y:tf.magnitude,color:'#476935',name:'Gain (dB)'}],'Bode numérique',true)+chart(tf.frequency,[{y:tf.phase,color:'#35677a',name:'Phase (°)'}],'Bode numérique',true):''}</section>`}).join('');
 const analysisSummary=analysis?{f0:analysis.f0,onset:analysis.onset,attack:analysis.attack,inharmonicity:analysis.inharmonicity,partials:analysis.partials}:null;
 const errorLabels:Record<string,string>={time:'Temps',spectral:'Spectre',spectrogram:'STFT',envelope:'Enveloppe',attack:'Attaque',total:'Pondérée'};
 const metrics=result?.errors?`<table><thead><tr>${Object.keys(result.errors).map(k=>`<th>${escape(errorLabels[k]||k)}</th>`).join('')}</tr></thead><tbody><tr>${Object.values(result.errors).map(v=>`<td>${v.toFixed(6)}</td>`).join('')}</tr></tbody></table>`:'<p>Aucune comparaison disponible.</p>';
 const metadata={file:audio?.metadata??null,start,duration:patch.duration,sample_rate:patch.sample_rate,weights};
 const reference=`<p><strong>${escape(audio?.metadata.name??'Création manuelle')}</strong> · sélection ${start.toFixed(3)}–${(start+patch.duration).toFixed(3)} s · ${(patch.sample_rate/1000).toFixed(1)} kHz · synthèse mono</p><p>Poids : ${Object.entries(weights).map(([k,v])=>`${escape(errorLabels[k])} ${v}`).join(' · ')}.</p>`;
 const html=`<!doctype html><html lang="fr"><meta charset="utf-8"><title>Rapport Résonant — ${escape(patch.name)}</title><style>body{font:15px/1.6 system-ui;max-width:1000px;margin:40px auto;color:#192833;padding:20px}h1{font-size:36px}h2{border-top:1px solid #b5c3cc;padding-top:20px}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{text-align:left;padding:10px;border-bottom:1px solid #d8e0e5}summary{cursor:pointer;font-weight:600;padding:12px 0}details{margin:12px 0}pre{background:#f3f5f7;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere}svg{width:100%;height:auto}figure{margin:20px 0;break-inside:avoid}section{break-inside:avoid}figcaption{font-weight:600}button{padding:12px 18px}@media print{button,.appendix{display:none}body{margin:0}details>summary{display:none}}</style><button onclick="document.querySelectorAll('details:not(.appendix)').forEach(d=>d.open=true);window.print()">Imprimer / enregistrer en PDF</button><h1>Résonant / Rapport de synthèse</h1><p>${escape(patch.name)} · ${new Date().toLocaleString('fr-FR')}</p><h2>Référence et sélection</h2>${reference}<details class="appendix"><summary>Métadonnées complètes</summary><pre>${escape(JSON.stringify(metadata,null,2))}</pre></details><h2>Graphe exécuté</h2>${graph}<h2>Mesures</h2>${metrics}<p>Erreurs relatives ; elles ne sont pas des pourcentages de ressemblance.</p><details class="appendix"><summary>Analyse détaillée et partiels</summary><pre>${escape(JSON.stringify(analysisSummary,null,2))}</pre></details>${plots}<h2>Équations et paramètres</h2><details><summary>Consulter les ${patch.nodes.length} blocs du modèle</summary>${math}</details><h2>Reproductibilité</h2><p>Les signaux ne sont pas normalisés. L’analyse utilise la moyenne des canaux. Les modèles sont des propositions interprétables, pas une identification physique unique. Exporter également le JSON ci-dessous et conserver le WAV original.</p><details class="appendix"><summary>Modèle JSON complet</summary><pre>${escape(JSON.stringify(patch,null,2))}</pre></details></html>`;
 return download(html,'resonant-rapport.html','text/html');
}
